# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/atomic-ideas',
                'doc_host': 'https://apereiral.github.io',
                'git_url': 'https://github.com/apereiral/atomic-ideas',
                'lib_path': 'atomic_ideas'},
  'syms': {'atomic_ideas.core': {'atomic_ideas.core.foo': ('core.html#foo', 'atomic_ideas/core.py')}}}
